from enum import StrEnum


class ScanStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMED_OUT = "TIMED_OUT"


class ScanStage(StrEnum):
    TARGET_VALIDATION = "TARGET_VALIDATION"
    HEALTH_CHECK = "HEALTH_CHECK"
    API_DISCOVERY = "API_DISCOVERY"
    API_NORMALIZATION = "API_NORMALIZATION"
    RELATIONSHIP_ANALYSIS = "RELATIONSHIP_ANALYSIS"
    PLAN_GENERATION = "PLAN_GENERATION"
    PLAN_VALIDATION = "PLAN_VALIDATION"
    MODULE_EXECUTION = "MODULE_EXECUTION"
    RESULT_VALIDATION = "RESULT_VALIDATION"
    REPORT_GENERATION = "REPORT_GENERATION"
    COMPLETED = "COMPLETED"


class StepStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ArtifactType(StrEnum):
    TARGET_PROFILE = "TARGET_PROFILE"
    NORMALIZED_API_GRAPH = "NORMALIZED_API_GRAPH"
    RELATIONSHIP_ANALYSIS = "RELATIONSHIP_ANALYSIS"
    SCAN_PLAN = "SCAN_PLAN"
    SCAN_RESULT = "SCAN_RESULT"
    EVIDENCE = "EVIDENCE"
    AI_REPORT = "AI_REPORT"
    PDF_REPORT = "PDF_REPORT"


class JobType(StrEnum):
    SCANNER = "SCANNER"
    RELATIONSHIP_ANALYSIS = "RELATIONSHIP_ANALYSIS"
    PLAN_GENERATION = "PLAN_GENERATION"
    MODULE_EXECUTION = "MODULE_EXECUTION"
    REPORT_GENERATION = "REPORT_GENERATION"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"


class Severity(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class ReportStatus(StrEnum):
    PENDING = "PENDING"
    GENERATING = "GENERATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class PlanStatus(StrEnum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


STAGE_PROGRESS: dict[ScanStage, int] = {
    ScanStage.TARGET_VALIDATION: 5,
    ScanStage.HEALTH_CHECK: 10,
    ScanStage.API_DISCOVERY: 30,
    ScanStage.API_NORMALIZATION: 40,
    ScanStage.RELATIONSHIP_ANALYSIS: 55,
    ScanStage.PLAN_GENERATION: 65,
    ScanStage.PLAN_VALIDATION: 70,
    ScanStage.MODULE_EXECUTION: 85,
    ScanStage.RESULT_VALIDATION: 90,
    ScanStage.REPORT_GENERATION: 99,
    ScanStage.COMPLETED: 100,
}

SEVERITY_RANK: dict[Severity, int] = {
    Severity.CRITICAL: 5,
    Severity.HIGH: 4,
    Severity.MEDIUM: 3,
    Severity.LOW: 2,
    Severity.INFO: 1,
}

